// Test statements: [text, trait (Big Five only), reversed (1 = reverse-scored)].
// Big Five items follow the Mini-IPIP (Donnellan et al., 2006), drawn from the public-domain IPIP pool.
module.exports = {
  'big-five': [
    ['I am the life of the party.', 'E', 0],
    ["I sympathize with others' feelings.", 'A', 0],
    ['I get chores done right away.', 'C', 0],
    ['I have frequent mood swings.', 'N', 0],
    ['I have a vivid imagination.', 'O', 0],
    ["I don't talk a lot.", 'E', 1],
    ["I am not interested in other people's problems.", 'A', 1],
    ['I often forget to put things back in their proper place.', 'C', 1],
    ['I am relaxed most of the time.', 'N', 1],
    ['I am not interested in abstract ideas.', 'O', 1],
    ['I talk to a lot of different people at parties.', 'E', 0],
    ["I feel others' emotions.", 'A', 0],
    ['I like order.', 'C', 0],
    ['I get upset easily.', 'N', 0],
    ['I have difficulty understanding abstract ideas.', 'O', 1],
    ['I keep in the background.', 'E', 1],
    ['I am not really interested in others.', 'A', 1],
    ['I make a mess of things.', 'C', 1],
    ['I seldom feel blue.', 'N', 1],
    ['I do not have a good imagination.', 'O', 1],
  ],
  'exam-stress': [
    ['My mind goes blank when I sit an exam.', null, 0],
    ['I lose sleep in the days before important tests.', null, 0],
    ['I feel tense when I start studying for an exam.', null, 0],
    ['I worry about my results more than about learning the material.', null, 0],
    ['Small mistakes during an exam upset me for a long time.', null, 0],
    ['I feel calm in the hour before an exam.', null, 1],
    ['I trust that my preparation will be enough.', null, 1],
    ['Exam periods make me feel overwhelmed.', null, 0],
  ],
  procrastination: [
    ['I start assignments close to the deadline.', null, 0],
    ['I get distracted by my phone while studying.', null, 0],
    ['I wait until I feel motivated before I begin.', null, 0],
    ['I leave small tasks unfinished for days.', null, 0],
    ['I plan my study time ahead and stick to it.', null, 1],
    ['I usually start work as soon as it is assigned.', null, 1],
    ['I tell myself I will do it later, then I do not.', null, 0],
    ['I finish tasks well before they are due.', null, 1],
  ],
  'career-interest': [
    ['I enjoy solving logic or technical problems.', null, 0],
    ['I like building or fixing things.', null, 0],
    ['I enjoy working with data or numbers.', null, 0],
    ['I like learning how systems work.', null, 0],
    ['I enjoy using software tools to create things.', null, 0],
    ['I find programming or engineering topics interesting.', null, 0],
    ['I prefer work with clear, measurable results.', null, 0],
    ['I get bored by technical or analytical tasks.', null, 1],
  ],
};
